//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp3Host.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectId", Namespace="http://schemas.datacontract.org/2004/07/MongoDB.Bson")]
    [System.SerializableAttribute()]
    public partial struct ObjectId : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _incrementField;
        
        private int _machineField;
        
        private short _pidField;
        
        private int _timestampField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _increment {
            get {
                return this._incrementField;
            }
            set {
                if ((this._incrementField.Equals(value) != true)) {
                    this._incrementField = value;
                    this.RaisePropertyChanged("_increment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _machine {
            get {
                return this._machineField;
            }
            set {
                if ((this._machineField.Equals(value) != true)) {
                    this._machineField = value;
                    this.RaisePropertyChanged("_machine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short _pid {
            get {
                return this._pidField;
            }
            set {
                if ((this._pidField.Equals(value) != true)) {
                    this._pidField = value;
                    this.RaisePropertyChanged("_pid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _timestamp {
            get {
                return this._timestampField;
            }
            set {
                if ((this._timestampField.Equals(value) != true)) {
                    this._timestampField = value;
                    this.RaisePropertyChanged("_timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMp3Service")]
    public interface IMp3Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/GetTitle", ReplyAction="http://tempuri.org/IMp3Service/GetTitleResponse")]
        string GetTitle(Mp3Host.ServiceReference1.ObjectId key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/GetTitle", ReplyAction="http://tempuri.org/IMp3Service/GetTitleResponse")]
        System.Threading.Tasks.Task<string> GetTitleAsync(Mp3Host.ServiceReference1.ObjectId key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/Index", ReplyAction="http://tempuri.org/IMp3Service/IndexResponse")]
        Mp3Service.Mp3File[] Index();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/Index", ReplyAction="http://tempuri.org/IMp3Service/IndexResponse")]
        System.Threading.Tasks.Task<Mp3Service.Mp3File[]> IndexAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/GetGenre", ReplyAction="http://tempuri.org/IMp3Service/GetGenreResponse")]
        Mp3Service.Mp3File[] GetGenre(string genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/GetGenre", ReplyAction="http://tempuri.org/IMp3Service/GetGenreResponse")]
        System.Threading.Tasks.Task<Mp3Service.Mp3File[]> GetGenreAsync(string genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/Generes", ReplyAction="http://tempuri.org/IMp3Service/GeneresResponse")]
        string[] Generes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/Generes", ReplyAction="http://tempuri.org/IMp3Service/GeneresResponse")]
        System.Threading.Tasks.Task<string[]> GeneresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/Artists", ReplyAction="http://tempuri.org/IMp3Service/ArtistsResponse")]
        string[] Artists(string Genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/Artists", ReplyAction="http://tempuri.org/IMp3Service/ArtistsResponse")]
        System.Threading.Tasks.Task<string[]> ArtistsAsync(string Genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/ALbums", ReplyAction="http://tempuri.org/IMp3Service/ALbumsResponse")]
        string[] ALbums(string Genre, string Artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/ALbums", ReplyAction="http://tempuri.org/IMp3Service/ALbumsResponse")]
        System.Threading.Tasks.Task<string[]> ALbumsAsync(string Genre, string Artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/GetMp3", ReplyAction="http://tempuri.org/IMp3Service/GetMp3Response")]
        System.IO.Stream GetMp3(Mp3Host.ServiceReference1.ObjectId key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMp3Service/GetMp3", ReplyAction="http://tempuri.org/IMp3Service/GetMp3Response")]
        System.Threading.Tasks.Task<System.IO.Stream> GetMp3Async(Mp3Host.ServiceReference1.ObjectId key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMp3ServiceChannel : Mp3Host.ServiceReference1.IMp3Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Mp3ServiceClient : System.ServiceModel.ClientBase<Mp3Host.ServiceReference1.IMp3Service>, Mp3Host.ServiceReference1.IMp3Service {
        
        public Mp3ServiceClient() {
        }
        
        public Mp3ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Mp3ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Mp3ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Mp3ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTitle(Mp3Host.ServiceReference1.ObjectId key) {
            return base.Channel.GetTitle(key);
        }
        
        public System.Threading.Tasks.Task<string> GetTitleAsync(Mp3Host.ServiceReference1.ObjectId key) {
            return base.Channel.GetTitleAsync(key);
        }
        
        public Mp3Service.Mp3File[] Index() {
            return base.Channel.Index();
        }
        
        public System.Threading.Tasks.Task<Mp3Service.Mp3File[]> IndexAsync() {
            return base.Channel.IndexAsync();
        }
        
        public Mp3Service.Mp3File[] GetGenre(string genre) {
            return base.Channel.GetGenre(genre);
        }
        
        public System.Threading.Tasks.Task<Mp3Service.Mp3File[]> GetGenreAsync(string genre) {
            return base.Channel.GetGenreAsync(genre);
        }
        
        public string[] Generes() {
            return base.Channel.Generes();
        }
        
        public System.Threading.Tasks.Task<string[]> GeneresAsync() {
            return base.Channel.GeneresAsync();
        }
        
        public string[] Artists(string Genre) {
            return base.Channel.Artists(Genre);
        }
        
        public System.Threading.Tasks.Task<string[]> ArtistsAsync(string Genre) {
            return base.Channel.ArtistsAsync(Genre);
        }
        
        public string[] ALbums(string Genre, string Artist) {
            return base.Channel.ALbums(Genre, Artist);
        }
        
        public System.Threading.Tasks.Task<string[]> ALbumsAsync(string Genre, string Artist) {
            return base.Channel.ALbumsAsync(Genre, Artist);
        }
        
        public System.IO.Stream GetMp3(Mp3Host.ServiceReference1.ObjectId key) {
            return base.Channel.GetMp3(key);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetMp3Async(Mp3Host.ServiceReference1.ObjectId key) {
            return base.Channel.GetMp3Async(key);
        }
    }
}
